DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TEAMHIERARCHY;
DROP TABLE IF EXISTS USERACCESS;

CREATE TABLE USER (
  EMPID VARCHAR(20) PRIMARY KEY,
  ACCESSKEY VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(2) NOT NULL
);

CREATE TABLE TEAMHIERARCHY(
  EMPID VARCHAR(250) PRIMARY KEY,
  MANAGERID VARCHAR(20) NOT NULL
);

CREATE TABLE USERACCESS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    EMPID VARCHAR(250) NOT NULL,
    ACCESSKEY VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(2) NOT NULL,
    SUBUSER VARCHAR(250) NOT NULL,
    SUBUSERACCESSKEY VARCHAR(20) NOT NULL,
    SUBUSERCOUNTRY VARCHAR(2) NOT NULL
);




